version: '2'

services:
  mysql:
    image: sameersbn/mysql:5.7.22-1
    env_file:
      - .env
    volumes:
      # NOTE: /srv/docker/redmine はもともと存在しないので、事前に作成することが必要。
      #       しかし mac では / は read only なので、 ./src にしました。
      - ./srv/docker/redmine/mysql:/var/lib/mysql
    # https://www.redmine.org/projects/redmine/wiki/MySQL_configuration
    command: --transaction-isolation=READ-COMMITTED

  redmine:
    build: ./
    image: sameersbn/redmine:5.1.2
    depends_on:
      - mysql
    env_file:
      - .env

    ports:
      - "10083:80"
    volumes:
      # NOTE: (同上)
      - ./srv/docker/redmine/redmine_mysql:/home/redmine/data
      - ./srv/docker/redmine/redmine-logs:/var/log/redmine
